version: '3.8'

services:
  neeric:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AWS_REGION=${AWS_REGION:-us-east-1}
    volumes:
      # Mount AWS credentials if available
      - ~/.aws:/home/neeric/.aws:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Development service
  neeric-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=development
      - VITE_AWS_REGION=${AWS_REGION:-us-east-1}
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.aws:/home/neeric/.aws:ro
    command: npm run dev
    profiles:
      - dev

networks:
  default:
    name: neeric-network 